---
title: "Felipe Pena Mosca"
---


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> penam003@umn.edu
- <i class="fa fa-github"></i> [github.com/fepenamosca](https://github.com/fepenamosca)


<i class="fa fa-book"></i> **Education** 
--------------------------------------------------------------------------------

- **Doctorate of Philosophy**   
<i class="fa fa-compass"></i> University of Minnesota, United States      
<i class="fa fa-calendar"></i> August 2019 - Present  
Major: Veterinary Medicine, Minor: Epidemiology  
Advisers: Luciano Caixeta & Sandra Godden

- **Master in Science**  
<i class="fa fa-compass"></i>Universidad de la República, Uruguay  
<i class="fa fa-calendar"></i> April 2016 - May 2019    
Major: Animal health  
Advisers: Ana Meikle & Elena de Torres  

- **Doctor in Veterinary Medicine**  
<i class="fa fa-compass"></i>Universidad de la República, Uruguay  
<i class="fa fa-calendar"></i>March 2010 - September 2015      
Advisers: Victoria de Brun & Ana Meikle  


<i class="fa fa-laptop"></i> **Professional Research & Teaching experience** 
--------------------------------------------------------------------------------

- **Graduate Research Assistant**
University of Minnesota, United States
August 2019 - Present

I currently work in planification, sampling, laboratory and data analysis in observational studies with the aim of improving dairy cows health and welfare; and find novel solutions for existent problems in dairy farms.

- **Milk Quality Technical Support**  
Conaprole, Uruguay  
July 2017 - July 2019

I worked for Conaprole (largest dairy industry in Uruguay) in Florida (Uruguay) advising dairy farmers about milk quality and mastitis control in dairy farms.

- **Research Assistant**  
Universidad de la República, Uruguay  
January 2016 - July 2019

I worked in the veterinary college at Universidad de la República for more than three years doing research, assisting in teaching veterinary college students and extension for dairy farmers.

- **Veterinary Practitioner**  
Uruguay  
October 2015 – July 2019

My work as a veterinarian was focused on dairy cows’ health and bovine mastitis control in dairy farms.

- **Veterinary Advising**  
La Constancia, Uruguay  
May 2015 - July 2015 & August 2018 - February 2019

I worked in pig health, reproduction and management in different parts of the farm.

- **Undergraduate Research Assistant**  
Universidad de la República, Uruguay  
August 2014 - July 2015  

I investigated the association between undernutrition and reproduction in sheep. I acquired training in techniques of radioimmunoassay, Immunoradiometric assay and real time PCR.
  
  
<i class="fa fa-award"></i> Honors & Awards 
--------------------------------------------------------------------------------

- **Veterinary Medicine program travel award**, University of Minnesota, 2021.

- **Graduate Student Professional Development Program**, Mn Drive Global Food Ventures, USA, 2021.

- **Fulbright Scholarship**, Fulbright Comission, Uruguay, 2018.

- **Scholarship for Young Teachers and Researchers**, Santander, Uruguay, 2017.

- **Graduate scholarship**, ANII (National research and innovation agency), Uruguay, 2016.

- **Introduction to research scholarship**, ANII (National research and innovation agency), Uruguay, 2014.

<i class="fa fa-book"></i> **Publications**
--------------------------------------------------------------------------------

- #### **Peer-reviewed**

##### - **Peña Mosca F.**, Dean C.,  Ray T., Heins B., Pinedo P. , Machado V., Caixeta L. , Noyes N. (2022). Could Udder Microbiome-based Products be Used as an Alternative Strategy for Mastitis Treatment and Prevention?. eOrganic . http://eorganic.org/node/35010

##### - Dean C., **Peña Mosca F.**, Ray T., Heins B., Pinedo P. , Machado V., Caixeta L. , Noyes N. (2021). What is the Microbiome and Why is it Important for Organic Livestock Production?. eOrganic. http://eorganic.org/node/34373

- #### **Published in conference proceedings**

##### - **Pena Mosca, F.**, Florentino, C.C., Rocha, C., Feijoo, V.C., Masic, A., Borchers, M., Asper, D., Caixeta, L.S.  (2022) .Investigation of the inclusion of on-farm measurement of somatic cell count and differential cell count in algorithms to predict cows with intramammary infections at dry-off. NMC 61st Annual Meeting Proceedings.

##### - Florentino, C.C., **Peña Mosca, F.**, Ruch, M., Mourad, M.M., Tikofsky, L., Godden, S.M., Caixeta, L.S. (2022). The effects of administration of acidogenic boluses at dry-off in udder health and milk yield in early lactation – interim results. NMC 61st Annual Meeting Proceedings.

##### - **Peña Mosca, F.**, Dean, C., Ray, T., Heins, B., Pinedo, P., Machado, V.S., Caixeta, L.S., Noyes, N.R. (2021). Association between bacterial group and persistence in the mammary gland in early lactation primiparous cows. Conference of Research Workers in Animal Diseases.

##### - Dean, C., **Peña Mosca F.**, Fernandes, L., Sharpe, K., Manriquez, D., Doster, E., Antunes Jr, A.M., Calles, V.F., Bauman, C., Wehri, T., Heins, B., Pinedo, P., Machado, V.S., Caixeta , L.S., Noyes, N.R., (2021). Longitudinal survey of the bovine teat microbiome. Conference of Research Workers in Animal Diseases. 

##### - **Peña Mosca, F.**, Dean, C.J., Caixeta, L.S., Ray, T., Heins, B., Machado, V.S., Pinedo, P.J., Noyes, N.R. (2021). Description of the intramammary infections dynamics in early lactation heifer on organic dairy farms. AABP 54th Annual conference.

##### - Rial, C., Laplacette, A.L., Perez, M.M., Florentino, C.C., **Peña Mosca, F.**, Caixeta, L.S., Giordano, J.O. (2021). Pattern of rumination time and physical activity captured by an ear-attached sensor around the time of clinical diagnosis of metritis and mastitis in dairy cows. ADSA Virtual Conference.

##### - Rial, C., Laplacette, A.L., Perez, M.M., Florentino, C.C., **Peña Mosca, F.**, Caixeta, L.S., Giordano, J.O. (2021) Pattern of rumination time and physical activity captured by an ear-attached sensor before, during and after the clinical diagnosis of metabolic-digestive disorders in lactating dairy cows". ADSA Virtual Conference.

##### - **Peña Mosca, F.**, Dean, C.J., Heins, B.J., Machado, V.S., Pinedo, P.J., Noyes, N.R., Caixeta, L.S.(2021). Description of Staphylococcus sp. intramammary infections in early lactation primiparous cows on organic dairy farms. ADSA Virtual Conference. 

##### - Florentino, C.C., Rodriguez, Z., Shepley, E., **Peña Mosca F.**, Cramer, G., Rial, C., Laplacette, A., Borchers, K., Asper, D., Borchers, M., Giordano, J.O., Caixeta, L.S. (2021). Does rumination behavior in the first week postpartum impact the association between beta-hydroxybutyrate and early lactation milk yield?. ADSA Virtual Conference. 

##### - **Peña Mosca F.**, Godden S,M., Royster E., Crooker B.A., Raynor P., Janni, K. (2021) Management of Recycled Manure Solids Bedding on Midwest Dairy Farms. Part 2 – Relationship Between Processing Method, Bedding Characteristics and Bedding Bacterial Count. NMC 60th Annual Meeting Proceedings.

##### - Godden S.M., **Peña Mosca F.**, Royster E., Crooker B.A., Raynor P., Janni, K. (2021) Management of Recycled Manure Solids Bedding on Midwest Dairy Farms. Part 1 – Relationship between processing method, udder health and production, and bedding bacterial counts. NMC 60th Annual Meeting Proceedings.

##### - **Peña Mosca F.**, Dean C., Ray T., Doster E, , Fernandes L., Antunes A., Sharpe K., Feijoo V., Baumann C., Wehri T., Heins B. , Pinedo P. , Machado V., Caixeta L. , Noyes N. (2021). Associations between intramammary infections caused by non-aureus Staphylococci, Streptococcus spp. and Streptococcus-like organisms and Staphylococcus aureus in early lactation on organic dairy cows. NMC 60th Annual Meeting Proceedings.

##### - Godden S.M., **Peña Mosca F.**, Royster E., Crooker B.A., Raynor P., Jan.ni, K. (2021) Investigation of the Relationship Between Method of Processing Recycled Manure Solids Bedding and Udder Health and Production on Midwest Dairy Farms. AABP 53rd Annual conference.

##### - **Peña Mosca F.**, de Torres E. (2020) Udder health during transition period in primiparous and multiparous cows in Uruguay. NMC 59th Annual Meeting Proceedings.

##### - de Torres E., **Peña Mosca F.**, Vidart M., Larumbe R. (2019)  Microorganismos asociados a mastitis clínica en Uruguay. Latinoamerican mastitis network 3rd annual meeting.

##### - **Peña Mosca F.**, de Torres Elena, García Pintos M., Villanueva A. 1 Silveira J.M. (2019). Relación entre la salud de la ubre en la lactancia y el recuento celular individual y el aislamiento bacteriológico en el secado. Latinoamerican mastitis network 3rd anual meeting.

##### - de Torres E.,Vera P., Benard L., **Peña Mosca F.**,  Vidart M., Larumbe R., Muñoz M. (2019) Evaluation of the Monthly Incidence Rate of Clinical Mastitis in Two Dairy Operations of Uruguay. NMC 58th Annual Meeting Proceedings.

##### - **Peña Mosca, F.**, Meikle, A., de Torres, E. (2018) Effect of stocking rate and grazing management on udder health in dairy cows.  NMC Milano, The international bovine mastitis conference proceedings.

##### - **Peña Mosca F.**, Martinez R., Lamanna A., de Torres E. (2018) Heat stress mitigation measures and udder health in dairy cows. NMC Milano, The international bovine mastitis conference proceedings, Milan, Italy.

##### - **Peña Mosca F.**, de Torres, E.  (2017). Estrés calórico y salud mamaria en vacas lecheras. 10th Veterinary Technical seminars, Veterinary College, Univeridad de la República, Uruguay.	

- #### **Non peer-reviewed**

##### - de Torres E., Fariña, S., Hirigoyen D., López T., Martinez R., Morales T., **Peña Mosca F.**,  Pla M., Torres I., Viana H. (2016) Sistemas para prevencion y control de mastitis. National institute of agricultural research. http://www.ainfo.inia.uy/digital/bitstream/item/6381/1/Sistema-de-gestion-para-el-control-y-prevencion-mastitis.-2016.pdf

##### - Garín G., **Peña Mosca, F.** (2015) Subnutrición en ovinos: efectos sobre la preñez y función uterina. Facultad de Veterinaria, Universidad de la República. Tesis de grado.https://www.colibri.udelar.edu.uy/jspui/handle/123456789/10259


<i class="fa fa-flask"></i> **Additional training**
--------------------------------------------------------------------------------

- **Internship in Milk Quality laboratory**  
<i class="fa fa-compass"></i>Universidad de Concepción, Chile.    
<i class="fa fa-calendar"></i>May 2018.

- **Internship in Laboratory Diagnosis of Infectious Diseases**  
<i class="fa fa-compass"></i>Universidad de Buenos Aires, Argentina.  
<i class="fa fa-calendar"></i>May 2016.

- **Internship in poultry production**
<i class="fa fa-compass"></i>Florida Agrarian School, Uruguay.  
<i class="fa fa-calendar"></i>November 2013.

